### ISSUE TITLE
Test 

### ISSUE THREAD

**Issue by NarongSao** [thearabbit/microfis#2]
phalkun	[11:02 AM]  
ID Type=National ID than ID Number is unique, Date វាយទៅអត់ចាប់យកតម្លៃដែលបានវាយ. (edited)

[11:06]  
hide submit date on disbuse

phalkun	[11:13 AM]  
នៅ Form Client ដាក់ optional លើ Prefix

[11:18]  
First repayment date ដាក់ ទៅមុខមួយខែនៃ Disbursement date

[11:22]  
Repaid frequency ដូរទៅ Interest Repayment frequency ហើយ Term ដាក់ខាងលើ Interest Repayment frequency (edited)

phalkun	[11:29 AM]  
Disbursement date  ត្រូវបង្ហាញកាលបរិច្ឆេទបច្ចុប្បន្ន

[11:33]  
Cycle auto increase and read only.

[11:36]  
Amount cannot exceed change to Amount can not exceed.

phalkun	[11:42 AM]  
Repayment General Form, Microfis Outstanding to Loan Outstanding

[11:44]  
Due Date ដាក់ថ្ងៃជាភាសាខ្មែរ

[11:45]  
hide Submit Date on Schedule

----- Yesterday November 17th, 2016 -----
phalkun	[10:18 AM]  
uploaded and commented on a file 
Repayment Schedule.xlsx
Excel Spreadsheet
Click to download
1 Comment
នៅលើ Form Disburse ពេល Submit អោយបើក new tab ដែលមានទំរង់តារាងសងប្រាក់ដូចក្នុុង Excel

phalkun	[11:18 AM]  
នៅលើ Repayment Prepay form change word repaid date to prepay date and title Repayment prepay to Prepay.

**Comment by thearabbit** [comment]
- [x] [11:02 AM]
- [ ] [11:06]: Keep, use for disbursement status (submit, check, approved...)
- [ ] [11:13 AM]: Agree
- [ ] [11:18]: first repayment date must be after disbursement date
- [ ] [11:22]: Keep
- [ ] [11:29]: OK
- [ ] [11:33]: OK, will correct after
- [ ] [11:36]: It check with product range amout
- [ ] [11:42 AM]: OK, "Loan Outstanding"
- [ ] [11:44]: OK
- [ ]
